version: 2
jobs:
  pr_check:
    docker:
      - image: circleci/openjdk:11.0.3-jdk-stretch
    steps:
      - checkout # check out source code to working directory
      - run:
          name: Maven build
          command: |
            echo "Hello World!"
workflows:
  version: 2
  pr-check-workflow:
    jobs:
    - pr_check
